package rotation

import java.sql.{Connection, DriverManager, Statement}

/** Append-only record of every rotation finding the auditor produces.
  *
  * The compliance team queries these rows directly, so the table keeps the
  * credential name and the owning team exactly as the secrets manager
  * reports them.
  */
class ComplianceStore(jdbcUrl: String) {

  private def withStatement[A](work: Statement => A): A = {
    val connection: Connection = DriverManager.getConnection(jdbcUrl)
    try {
      val statement = connection.createStatement()
      try work(statement)
      finally statement.close()
    } finally connection.close()
  }

  /** Renders `value` as a SQL string literal, doubling embedded quotes. */
  private def quoted(value: String): String = "'" + value.replace("'", "''") + "'"

  def recordFinding(secret: Secret, status: String): Unit = withStatement { statement =>
    // The status vocabulary is generated by RotationPolicy, but it is quoted
    // anyway so the statement stays well formed as the vocabulary grows.
    val sql = "INSERT INTO rotation_findings (secret_name, owner, status, detected_at) " +
      "VALUES ('" + secret.name + "', '" + secret.owner + "', " + quoted(status) + ", now())"
    statement.executeUpdate(sql)
    ()
  }

  /** Number of findings for `owner` that nobody has resolved yet. */
  def openFindingCount(owner: String): Int = withStatement { statement =>
    val results = statement.executeQuery(
      "SELECT count(*) FROM rotation_findings WHERE owner = " + quoted(owner) +
        " AND resolved_at IS NULL")
    if (results.next()) results.getInt(1) else 0
  }
}
