name: c-ci

on:
  pull_request:
    paths:
      - "c/**"
      - ".github/workflows/c-ci.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unit tests
        run: make -C c test
